-- ============================================================
-- RETRO_SNAP — Redeem codes + Admin PIN (server-verified)
-- Applies to Supabase project: zualrdvvlcoexqrbedhl
-- Client contracts:
--   redeem_validate  -> {valid: bool, error: string|null}
--   redeem_use       -> {success: bool}
--   redeem_generate  -> [{code, batch_id, expires_at}, ...]
--   redeem_list      -> [{code, batch_id, is_used, used_at, expires_at, created_at}, ...]
--   admin_verify     -> {valid: bool}
-- All functions are SECURITY DEFINER + RLS blocks direct table access.
-- ============================================================

create extension if not exists pgcrypto;

-- ======================== TABLES ========================

create table if not exists public.redeem_codes (
    id         bigint generated by default as identity primary key,
    code       text not null unique,
    batch_id   uuid not null default gen_random_uuid(),
    is_used    boolean not null default false,
    used_at    timestamptz,
    expires_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.admin_pins (
    id        bigint generated by default as identity primary key,
    pin_hash  text not null,
    created_at timestamptz not null default now()
);

-- ======================== RLS (block direct anon access) ========================

alter table public.redeem_codes enable row level security;
alter table public.admin_pins enable row level security;

drop policy if exists redeem_codes_no_access on public.redeem_codes;
drop policy if exists admin_pins_no_access on public.admin_pins;

create policy redeem_codes_no_access on public.redeem_codes for all using (false);
create policy admin_pins_no_access on public.admin_pins for all using (false);

-- ======================== HELPERS ========================

create or replace function public.admin_key_ok(p_key text)
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.admin_pins
        where p_key <> '' and p_key = crypt(p_key, pin_hash)
    );
$$;

-- ======================== ADMIN AUTH ========================

create or replace function public.admin_verify(p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_valid boolean;
begin
    if p_pin is null or p_pin = '' then
        return jsonb_build_object('valid', false);
    end if;
    select exists (
        select 1 from public.admin_pins
        where p_pin = crypt(p_pin, pin_hash)
    ) into v_valid;
    return jsonb_build_object('valid', v_valid);
end;
$$;

-- ======================== REDEEM CODES ========================

create or replace function public.redeem_validate(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_row public.redeem_codes%rowtype;
begin
    select * into v_row from public.redeem_codes
    where code = upper(trim(coalesce(p_code, '')));

    if not found then
        return jsonb_build_object('valid', false, 'error', 'not_found');
    end if;
    if v_row.is_used then
        return jsonb_build_object('valid', false, 'error', 'already_used');
    end if;
    if v_row.expires_at is not null and v_row.expires_at <= now() then
        return jsonb_build_object('valid', false, 'error', 'expired');
    end if;
    return jsonb_build_object('valid', true, 'error', null);
end;
$$;

create or replace function public.redeem_use(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_updated int;
begin
    update public.redeem_codes
    set is_used = true, used_at = now()
    where code = upper(trim(coalesce(p_code, '')))
      and is_used = false
      and (expires_at is null or expires_at > now());
    get diagnostics v_updated = row_count;
    return jsonb_build_object('success', v_updated > 0);
end;
$$;

create or replace function public.redeem_generate(
    p_count        int default 50,
    p_expires_days int default 7,
    p_admin_key    text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_batch uuid := gen_random_uuid();
    v_codes text[] := '{}';
    v_code  text;
    i       int;
begin
    if not public.admin_key_ok(p_admin_key) then
        return jsonb_build_object('success', false, 'error', 'unauthorized');
    end if;

    p_count := least(greatest(coalesce(p_count, 0), 1), 500);

    for i in 1..p_count loop
        loop
            v_code := chr(65 + floor(random() * 26)::int)
                   || chr(65 + floor(random() * 26)::int)
                   || lpad(floor(random() * 10000)::int::text, 4, '0');
            exit when not exists (select 1 from public.redeem_codes where code = v_code);
        end loop;
        v_codes := v_codes || v_code;
    end loop;

    insert into public.redeem_codes (code, batch_id, expires_at)
    select unnest(v_codes), v_batch, now() + make_interval(days => p_expires_days);

    return coalesce((
        select jsonb_agg(jsonb_build_object(
            'code', code,
            'batch_id', batch_id::text,
            'expires_at', expires_at
        ) order by code)
        from public.redeem_codes
        where batch_id = v_batch
    ), '[]'::jsonb);
end;
$$;

create or replace function public.redeem_list(p_admin_key text default '')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.admin_key_ok(p_admin_key) then
        return '[]'::jsonb;
    end if;

    return coalesce((
        select jsonb_agg(jsonb_build_object(
            'code', code,
            'batch_id', batch_id::text,
            'is_used', is_used,
            'used_at', used_at,
            'expires_at', expires_at,
            'created_at', created_at
        ) order by created_at desc)
        from public.redeem_codes
    ), '[]'::jsonb);
end;
$$;

-- ======================== SEED DEFAULT ADMIN PIN ========================
-- Default PIN: 1234  (bcrypt cost 10) — CHANGE AFTER FIRST LOGIN.
insert into public.admin_pins (pin_hash)
select '$2b$10$F0WiuRKnQoaNQJ2EAN1suOEeFbC5s0uq/hby4fXdV79.czI8u0Zk6'
where not exists (select 1 from public.admin_pins);

-- ======================== GRANTS ========================

grant execute on function public.admin_verify(text) to anon;
grant execute on function public.redeem_validate(text) to anon;
grant execute on function public.redeem_use(text) to anon;
grant execute on function public.redeem_generate(int, int, text) to anon;
grant execute on function public.redeem_list(text) to anon;
